version: '3.8'

services:
  jungle-escape-core:
    build:
      context: ./jungle-escape-core
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./jungle-escape-core:/app
    depends_on:
      - jungle-escape-server
    networks:
      - ingress-network

  jungle-escape-server:
    build:
      context: ./jungle-escape-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./jungle-escape-server:/app
    networks:
      - ingress-network

networks:
  ingress-network:
    driver: bridge
