name: get jungle-escape-core

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Request Export
      id: request_export
      env:
        ACCESS_TOKEN: ${{ secrets.PLAYCANVAS_ACCESS_TOKEN }}
      run: |
        RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                   -H "Content-Type: application/json" \
                   -X POST \
                   -d '{"project_id": 1185257, "scenes": [1940847,1940848], "name": "jungle-escape-core"}' \
                   "https://playcanvas.com/api/apps/download")
        JOB_ID=$(echo $RESPONSE | jq -r '.id')
        echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

    - name: Poll Export Status
      env:
        ACCESS_TOKEN: ${{ secrets.PLAYCANVAS_ACCESS_TOKEN }}
      run: |
        POLL_STATUS="running"
        while [ "$POLL_STATUS" != "complete" ]; do
          RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                     "https://playcanvas.com/api/jobs/${JOB_ID}")
          POLL_STATUS=$(echo $RESPONSE | jq -r '.status')
          if [ "$POLL_STATUS" == "error" ]; then
            echo "Error in job processing"
            exit 1
          fi
          echo "Current status: $POLL_STATUS"
          sleep 5
        done
        DOWNLOAD_URL=$(echo $RESPONSE | jq -r '.data.download_url')
        echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV

    - name: Download and Replace Directory
      run: |
        curl -L "${DOWNLOAD_URL}" -o project.zip
        unzip -o project.zip -d temp-project
        rm -rf jungle-escape-core
        mv temp-project jungle-escape-core
        rm -rf project.zip

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add jungle-escape-core
        git commit -am "Playcanvas project updated via Github Actions"
        git push
